#define GAME_OF_LIFE "   ************************ Game of Life **************************"
#define END_OF_MENU "   ****************************************************************"
#define THE_R_PENTINO_MENU " *   1 - The R-pentino                                              *"
#define DIE_HARD_MENU "*    2 - DieHard                                                     *"
#define ACORN_MENU " *   3 - Acorn                                                      *"
#define EXIT_MENU "  *  0 - Exit                                                      *"
#define TYPE "Type one of the options: "
#define OPTIONS_AVAILABLES "  * # Options Availables                                           *"
#define OPTION_SELECTED "Option Selected: -"
#define ERROR_OPTION "The Option Selected does not exist"
#define THE_R_PENTINO "The R-pentino"
#define ACORN "Acorn"
#define DIE_HARD "DieHard"
